building fundraiser page relates #10
GSG-CF05/DonationAPP-team-9 pull request #11
Opened 2022-02-08 20:19 UTC by ahmedkhilla

2022-02-08 20:23 UTC, ayaenshasy2002 approved these changes, later dismissed

2022-02-08 21:11 UTC, yahya-1 approved these changes

2022-02-08 21:11 UTC, yahya-1 approved these changes, later dismissed

2022-02-09 06:33 UTC, Ahmed-jebara approved these changes

2022-02-09 06:35 UTC, Ahmed-jebara approved these changes

2022-02-09 06:37 UTC, Ahmed-jebara approved these changes, later dismissed

2022-02-09 10:03 UTC, emanjaber requested changes
Great job Ahmad!
Make the changes I mentioned

2022-02-09 10:03 UTC, emanjaber commented on fundraiser1/fundraiser1.html
> +              alt=""
You have to edit the `src` of the image.

This is the correct way to write it:
`src="../asstes/photo-children.png"`

And the same for all the images, I will mark them with **(1)**

2022-02-09 10:03 UTC, emanjaber commented on fundraiser1/fundraiser1.html
> +                <img src="/DonationAPP-team-9/asstes/timer-icon.png" alt="" />
**(1)**
`src="../asstes/timer-icon.png"`

2022-02-09 10:03 UTC, emanjaber commented on fundraiser1/fundraiser1.html
> +              />
**(1)**
edit `src` for these 4 images

Also, you need to make the images "in-line" at mobile size

2022-02-09 10:03 UTC, emanjaber commented on fundraiser1/fundraiser1.html
> +              />
**(1)**
edit `src` of this image

2022-02-09 10:03 UTC, emanjaber commented on fundraiser1/fundraiser1.css
> +@import url("https://cdn.jsdelivr.net/npm/@xz/fonts@1/serve/metropolis.min.css%22%22");
Delete `%22%22` from the end of the link, so the site will recognize the font

2022-02-09 10:03 UTC, emanjaber commented on fundraiser1/fundraiser1.css
> +  background-color: #e5e5e5;
Change `background-color` into `#FBFBFB` so it will be like the design

2022-02-09 10:03 UTC, emanjaber commented on fundraiser1/fundraiser1.css
> +}
Make the color font white
`  color: #fff;`

2022-02-09 11:01 UTC, ayaenshasy2002 approved these changes

2022-02-09 11:10 UTC, emanjaber approved these changes
**Well done Ahmad! 🎉**

2022-02-09 12:00 UTC, Ahmed-jebara approved these changes

2022-02-09 12:57 UTC, yahya-1 approved these changes

2022-02-09 12:57 UTC, merged